path: C:\Users\dilek\modelEgitimiYeni\data
train: train
val : validation

# Keypoints
kpt_shape: [10, 2] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [ 1,3,2, 4, 5, 6, 7, 8, 9,10]


names:
  0: fish
  
